wandb_version: 1

epochs:
  desc: null
  value: 10000
batch_size:
  desc: null
  value: 1024
learning_rate:
  desc: null
  value: 2.0e-05
n_hidden_unit_list:
  desc: null
  value:
  - 20
  - 20
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700192619.001191
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      8:
      - 1
      - 5
      13: linux-x86_64
